name: mcumgr_flutter_example
description: Demonstrates how to use the mcumgr_flutter plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  uuid: ^4.2.1
  json_serializable: ^6.7.1
  provider: ^6.1.1
  flutter:
    sdk: flutter

  mcumgr_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/
